### ISSUE TITLE
Add mbed TLS 2.X (2.4+) support to bmx7

### ISSUE THREAD

**Issue by diizzyy** [axn/bmx6#10]
@axn 
Hi,

As mbed TLS 1.3 is EoL is there a chance if you could look into adding support for the 2.4+ versions instead for bmx7?

Best regards,
Daniel

**Comment by axn** [comment]
bmx7 supports mbedtls.2.4.0 since https://github.com/axn/bmx6/commit/9b48f758cbbe3c88688a77b0255ada05974bd608

bmx7/Makefile in openwrt-routing master branch got updated to use mbedtls.2.4.0 now

Thanks for the hint.
