### ISSUE TITLE
release tags would help Debian packaging

### ISSUE THREAD

**Issue by smoe** [axn/bmx6#3]
Hello,
I would happily upload bmx6 to Debian. I am somewhat uncertain if you consider that favourable for your project (you may want people to work as close to your source tree as possible). 
I happily team-maintain that package with someone closer to the developers or hand the package over to that individual after a first upload.
Best,
Steffen

**Comment by axn** [comment]
I appreciate a lot your suggestion. Would you mind recreating the issue in bmx-routing/bmx6 space here: https://github.com/bmx-routing/bmx6 ? I want to close this project at axn space soon.
