### ISSUE TITLE
BMX7-0.1-alpha-rev41aabcb terminates on SIGSEGV -502124

### ISSUE THREAD

**Issue by janos4276** [axn/bmx6#8]
Hi,

I'm using BMX7-0.1-alpha-rev41aabcb on a 802.11s mesh consisting of two nodes. The OS is OpenWRT 15.05 with the latest patches, and the configuration is the same for both nodes.

About every three minutes bmx7 would terminate with the following error:
daemon.err bmx7[9395]: ERROR First SIGSEGV -502124 received, try cleaning up...
daemon.err bmx7[9395]: ERROR Terminating with error code -502124 (BMX7-0.1-alpha-rev41aabcb)! Please notify a developer

The output of bmx7 -c parameters for one of the nodes is:
 plugin                 bmx7_config.so       (0)
 plugin                 bmx7_sms.so          (0)
 plugin                 bmx7_iwinfo.so       (0)
 plugin                 bmx7_tun.so          (0)
 plugin                 bmx7_table.so        (0)
 ipVersion              6                    (6)
 dev                    wdmesh0              (0)
 syncSms                mdns                 (0)
 tunOutTimeout          120000               (60000)
 tunMtu                 1528                 (0)
 tunDev                 dmesh                (0)
    /tun4Address        10.254.177.170/32    (0)
    /tun6Address        2012:0:0:b1aa::1/64  (0)
 tunOut                 sen4                 (0)
    /network            10.254.0.0/16        (0)
    /hysteresis         30                   (20)
 tunOut                 sen6                 (0)
    /network            2012::/48            (0)
    /hysteresis         30                   (20)
 tunOut                 inet4                (0)
    /network            0.0.0.0/0            (0)
    /maxPrefixLen       0                    (128)

I'm pretty much at loss on how I can debug this further, but if you need more info please let me know.

Cheers,

Jan

**Comment by axn** [comment]
Hi Jan

Interesting, thanks for the hint.

Do you get cores (check for /tmp/bmx7.*.core) ?
If yes please send me and tell me the architecture of your device.
That would help a lot to debug.

If not, could you check if the crash persist when plugins are disabled?

thanks /axel

**Comment by axn** [comment]
Hi again,

I guess its fixed with revision
http://bmx6.net/projects/bmx6/repository/revisions/9406a533123bd4af00d1b345a85b14fc175c48f8
which is also included in latest openwrt-routing feeds (for-15.05 and
master).

Would be nice if you can check,
thanks
/axel

**Comment by janos4276** [comment]
Hi Axel,

Apologies for the late reply. It's been a bit hectic here.

I'll check it. Just in case, I've attached a core dump. 

Oh yeah, the architecture is:

system type		: Atheros AR9344 rev 2
machine			: WD My Net N600
processor		: 0
cpu model		: MIPS 74Kc V4.12
BogoMIPS		: 278.93
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa			: mips1 mips2 mips32r1 mips32r2
ASEs implemented	: mips16 dsp dsp2
shadow register sets	: 1
kscratch registers	: 0
package			: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available

I also noticed something else at some point in the logs. When I don't compile some plugins, I get a warning that the plug-ins might not be up to date and bmx7 terminates. I think this happens when the rsa key is generated for the first time. I'll see if I can reproduce it ... Maybe it's also already fixed with the latest version.

[bmx7.12386.11.1467289353.core.zip](https://github.com/axn/bmx6/files/344042/bmx7.12386.11.1467289353.core.zip)

**Comment by janos4276** [comment]
Hi Axel,

OK, so I had fetched and compiled the latest OpenWRT 15.05 patches and the latest revision of BMX7 (with only the recommended plugins: bmx7-iwinfo, bmx7-tun, and bmx7-uci-config) last weekend. Things have been running quite stable and I can confirm that this issue is fixed. Thanks!

However, for the following configuration:

WAN --------------- Node 1 ------------------ Node 2 --------------------- Node 3

, where Node 3 is inside the signal range of Node 2 and outside the signal range of Node 1, I get the following error message on Node 2 when I try to ping Node 3 from Node 1:

ip6_tunnel: X7Out_1743423A: Path to destination invalid or inactive!

This tunnel shows up as a link (shortId  1743423A) between Node 2 and Node3, but not on Node 1, when I execute bmx7 -cd8. It does however show up as a available tunnel on Node 1. I also get a similar error on Node 2 when I ssh into Node 3 via Node 2 and try to ping Node 1:

ip6_tunnel: X7Out_2CFAFF88: Path to destination invalid or inactive!

where this is a tunnel/link between Node 1 and Node 2 (shortId 1743423A.)

The configuration is the same as before, except that haven't compiled the other plug-ins.

Cheers,

Jan

**Comment by axn** [comment]
Hi,
I haven't seen this error before but will try to reproduce it.
Therefore, can you help me with following questions:
Where does the errors appear (e.g. bmx7 -d0, dmesg, logread)?
Can you dump the output of "bmx7 -c parameters -d8" and "ip address" of
Node 1 and Node 3?
Which address are you using for pinging and ssh and which pinged address
triggers the error? Are the tunnel addresses pingable eventually?



Thanks
/axel

**Comment by janos4276** [comment]
Hi Axel,

The error appeared in logread and I was using the IPv4 addresses I had assigned to them for ping and ssh. Anyhow, this turns out to have been a false alarm. On a hunch/gut feeling, I have slept a night on it ;), I have added the following to the firewall configuration of Node 2:

config zone 'mesh'
        option name 'mesh'
        option input 'ACCEPT'
        option output 'ACCEPT'
        option forward 'ACCEPT'
        option mtu_fix '0'
        option conntrack '1'
        option masq '1'
        option family 'any'
        option device 'wmesh'
        option log '1'

The errors are gone, and I can now ping Node 3 from Node 1 and vice verse. SSH also works :)
I'll close this issue.

A bit off topic, but how does trusted nodes work?

Thanks for help and for BMX7!

Cheers,

Jan

**Comment by axn** [comment]
On 07.07.2016 11:24, janos4276 wrote:
> Hi Axel,
> 
> The error appeared in logread and I was using the IPv4 addresses I had
> assigned to them for ping and ssh. Anyhow, this turns out to have been a
> false alarm. On a hunch/gut feeling, I have slept a night on it ;), I
> have added the following to the firewall configuration of Node 2:
> 
> config zone 'mesh'
> option name 'mesh'
> option input 'ACCEPT'
> option output 'ACCEPT'
> option forward 'ACCEPT'
> option mtu_fix '0'
> option conntrack '1'
> option masq '1'
> option family 'any'
> option device 'wmesh'
> option log '1'
> 
> The errors are gone, and I can now ping Node 3 from Node 1 and vice
> verse. SSH also works :)
> I'll close this issue.
> 
> A bit off topic, but how does trusted nodes work?

Would you mind continuing to share your experience and question on:
https://lists.bmx6.net/cgi-bin/mailman/listinfo/bmxd

thanks.

/axel

**Comment by janos4276** [comment]
:) No problem. I think the certificate for https://lists.bmx6.net/cgi-bin/mailman/listinfo/bmxd needs to be updated. Chrome gives me a ERR_CERT_AUTHORITY_INVALID exception.

**Comment by axn** [comment]
On 07.07.2016 13:12, janos4276 wrote:
> :) No problem. I think the certificate for
> https://lists.bmx6.net/cgi-bin/mailman/listinfo/bmxd needs to be
> updated. Chrome gives me a ERR_CERT_AUTHORITY_INVALID exception.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/axn/bmx6/issues/8#issuecomment-231049641>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABQQnj0-slxXQs5Ec8stPtNTzjAa4i95ks5qTN8FgaJpZM4JCGus>.
> 

it should be self signed and for dabax.net domain who hosted this list.
You can also reach it via:
https://mail.dabax.net/cgi-bin/mailman/listinfo/bmxd

/axel
